-- =========================================================
-- Datos semilla: campos migrados desde 'Calendario CyG 140826.xlsx'
-- Generado automáticamente a partir de la planilla real (ago-2026).
-- Ejecutar DESPUÉS de 001_schema.sql.
-- supervisor_habitual_id queda NULL a propósito: se completa con
-- 003_asignar_supervisores.sql una vez que existan los usuarios reales.
-- =========================================================

insert into public.campos (nombre, cliente, zona, superficie_ha, meta_mensual, supervisor_habitual_nombre, notas) values
  ('EXCER 4 campos', 'Excer', 'San Esteban', 275.0, 1.0, NULL, 'Sin historial de visitas claro en la planilla original; confirmar supervisor habitual.'),
  ('EL RETORNO', 'Garces', 'San Esteban', 67.79, 2.0, 'Javier', NULL),
  ('EL TRIUNFO', 'Garces', 'San Esteban', 51.538, 2.0, 'Javier', NULL),
  ('PANQUEHUE', 'Garces', 'Panquehue', 76.68, 2.0, 'Javier', NULL),
  ('EXCER 3 campos', 'EXCER', 'Los Andes', 105.0, 1.0, 'Javier', NULL),
  ('LOS ENCINOS', 'Garces', 'Melipilla', 88.96, 1.0, 'Esteban', NULL),
  ('SAN JOSE', 'Javier Valdes', 'Melipilla', 230.0, 2.0, NULL, 'Sin historial de visitas claro en la planilla original; confirmar supervisor habitual.'),
  ('AGROALTO', 'Andres Aliaga', 'Maria Pinto', 684.0, 3.0, 'Javier', NULL),
  ('EXCER 1 campo', 'excer', 'Maria Pinto', 32.0, 0.0, NULL, 'Sin historial de visitas claro en la planilla original; confirmar supervisor habitual.'),
  ('SANTA CARMEN', 'Carmen Garcia', 'Chicureo', 58.0, 2.0, 'Javier', NULL),
  ('AGRICOLA METROPOLITANA', 'Felipe Jara ', 'Batuco ', 20.0, 2.0, 'Javier', NULL),
  ('EXCER 1 campo', 'EXCER', 'colina', 95.0, 1.0, 'Javier', NULL),
  ('LAMPA', 'Diego Ruiz Tagle', 'Lampa', NULL, 0.5, 'Javier', NULL),
  ('TIL-TIL', 'Diego Ruiz Tagle', 'Lampa', NULL, 0.5, 'Javier', NULL),
  ('LIRAY', 'Diego Ruiz Tagle', 'RM Norte', 69.0, 0.5, 'Javier', NULL),
  ('POLPAICO', 'Frutexa 2', 'Polpaico', 93.0, 1.0, 'Javier', NULL),
  ('PIRQUE', 'Sutil ', 'RM Sur', 269.0, 1.0, 'Cesar', NULL),
  ('SANTA REBECA', 'Sutil ', 'RM Sur', NULL, 1.0, 'Javier', NULL),
  ('MILLACURA', 'Sutil ', 'RM Sur', NULL, 1.0, 'Javier', NULL),
  ('SANTA PAULINA', 'Sutil ', 'RM Sur', NULL, 1.0, 'Cesar', NULL),
  ('SANTA EMA', 'Sutil ', 'RM Sur', NULL, 1.0, 'Cesar', NULL),
  ('SANTA FLORA', 'Sutil ', 'RM Sur', NULL, 1.0, 'Cesar', NULL),
  ('EL CIPRES-EL PORTON', 'Cristian Araos', 'RM Sur', 33.0, 1.0, 'Cesar', NULL),
  ('LA VEGA', 'David del Curto ', 'RM Norte', NULL, 1.0, 'Cesar', NULL),
  ('BUIN-PAINE', 'Frutexa 2', 'Buin', 107.0, 2.0, 'Javier', NULL),
  ('SAN JOSE BUIN', 'San Jose Buin', 'Buin', NULL, 1.0, 'Javier', NULL),
  ('SANT A CAMILA', 'Ignacio Miquel', 'RM Sur', 101.0, 2.0, 'Javier', NULL),
  ('LA MORERA', 'Garces', 'Graneros', 90.61, 1.0, 'Jose Miguel', NULL),
  ('SANTA MONICA', 'Garces', 'Graneros', 30.4, 1.0, 'Jose Miguel', NULL),
  ('SAN HERNAN', 'Garces', 'Graneros', 81.16, 1.0, 'Jose Miguel', NULL),
  ('CASTORES', 'Frutexa', 'Rancagua', 80.0, 2.0, 'Javier', NULL),
  ('SANTA ELENA', 'Frutexa', 'Rancagua', 245.0, 2.0, 'Javier', NULL),
  ('MOSTAZAL', 'Frutexa', 'Rancagua', NULL, 2.0, 'Javier', NULL),
  ('CALLEJONES', 'Frutexa', 'Rancagua', NULL, 2.0, 'Javier', NULL),
  ('EL PARQUE', 'Garces', 'Mostazal', 71.71, 2.0, 'Javier', NULL),
  ('EL RECURSO', 'Garces', 'Mostazal', 108.27, 2.0, 'Javier', NULL),
  ('SANTA MARGARITA', 'Garces', 'Mostazal', 184.0, 2.0, 'Javier', NULL),
  ('TALHUEN', 'Zunino', 'Maria Pinto', 93.0, 2.0, 'Javier', NULL),
  ('SEMILLERO', 'Zunino', 'Maria Pinto', NULL, 2.0, 'Javier', NULL),
  ('SAN DIEGO-CHOLQUI-CHOCALAN', 'Santa Magdalena', 'Melipilla', 400.0, 3.0, 'Javier', NULL),
  ('LA ROBLERIA', 'Garces', 'Aculeo', 19.66, 0.0, NULL, 'Sin historial de visitas claro en la planilla original; confirmar supervisor habitual.'),
  ('COCALAN', 'Garces', 'Las Cabras', 40.86, 1.0, 'Javier', NULL),
  ('ALMAHUE', 'Garces', 'Pichidegua', 252.88, 2.0, 'Javier', NULL),
  ('MAXAGRO', 'MaxAgro', 'Pichidegua', 200.0, 2.0, 'Javier', NULL),
  ('LAS CABRAS', 'Garces', 'Las Cabras', 72.78, 1.0, 'Javier', NULL),
  ('LA ESPERANZA', 'Garces', 'Las Cabras', 111.59, 1.0, 'Javier', NULL),
  ('LOS MAITENES', 'Garces', 'Las Cabras', 23.99, 1.0, 'Esteban', NULL),
  ('RAPEL', 'Zunino', 'Rapel', 135.0, 2.0, 'Esteban', NULL),
  ('HUILLICO', 'Juan Pablo De la Fuente', 'Maria Pinto', 300.0, 2.0, 'Javier', NULL),
  ('CASAS DEL BOSQUE', 'Casas del Bosque', 'Casa Blanca', 130.0, 2.0, 'Javier', NULL),
  ('ESTERO SAN LUIS', 'Nicolas Osandon', 'Coltauco', 46.0, 2.0, 'Esteban', NULL),
  ('SANTA LAURA', 'Monte Alegre', 'Mostaza', 98.0, 2.0, 'Esteban', NULL),
  ('PATAGUAL', 'Monte Alegre', 'Coltauco', NULL, 2.0, 'Esteban', NULL),
  ('ALSACIA-VIÑA MARIA-ALSACIA KIWIS', 'David del Curto ', 'San Vicente', 49.0, 2.0, 'Esteban', NULL),
  ('EXCER 3 CAMPOS', 'EXCER', 'SAN VICENTE', 145.0, 1.0, 'Esteban', NULL),
  ('PUQUIO', 'Pablo Sanchez', 'San Vicente', NULL, 2.0, 'Jose Miguel', NULL),
  ('QUINTA TILCOCO', 'Pablo Sanchez', 'San Vicente', NULL, 2.0, 'Jose Miguel', NULL),
  ('LIMAHUE', 'Pablo Sanchez', 'San Vicente', 96.2, 2.0, 'Jose Miguel', NULL),
  ('El ARROYO', 'Agustin Ureta', 'San Vicente', 53.0, 1.0, 'Esteban', NULL),
  ('COINCO', 'David del Curto ', 'coltauco', 243.0, 2.0, 'Jose Miguel', NULL),
  ('LA GLORIA', 'David del Curto ', 'coltauco', NULL, 2.0, 'Jose Miguel', NULL),
  ('OREGON ROSARIO', 'Ricardo Haz', 'Rosario-Rengo', 7.8, 1.0, 'Jose Miguel', NULL),
  ('EL RETIRO', 'Garces', 'Rosario-Rengo', 36.68, 1.0, 'Jose Miguel', NULL),
  ('ENTRE RIOS', 'Garces', 'San Fernando', 98.99, 1.0, 'Esteban', NULL),
  ('PUENTE NEGRO', 'Garces', 'San Fernando', 35.44553459, 1.0, 'Esteban', NULL),
  ('RIO CLARO', 'Garces', 'San fernando', 48.62, 1.0, 'Esteban', NULL),
  ('CK2', 'Cristian Araos', 'Santa Cruz', 21.5, 1.0, 'Esteban', NULL),
  ('KUNAKO', 'Cristian Araos', 'Santa Cruz', 73.0, 0.0, 'Esteban', NULL),
  ('EL TOCO 1-2', 'Ricardo Haz', 'Santa Cruz', 9.6, 0.0, 'Esteban', NULL),
  ('FUNCO LAS ARAÑAS', 'Cristóbal Crespo', 'Santa Cruz', 300.0, 2.0, 'Esteban', NULL),
  ('EL PEUMO', 'El Peumo ', 'Santa Cruz', 26.8, 2.0, 'Jose Miguel', NULL),
  ('KANKURA', 'Jose Manuel Pozo ', 'Santa Cruz', 69.0, 2.0, 'Jose Miguel', NULL),
  ('CALEUCHE', 'José Tomás Fernandez 1', 'Santa Cruz', 46.0, 1.0, 'Jose Miguel', NULL),
  ('CALLEUQUE', 'Garces', 'Colchagua', 13.24, 1.0, 'Jose Miguel', NULL),
  ('LA ESTACION', 'Garces', 'Colchagua', 169.98, 1.0, 'Jose Miguel', NULL),
  ('TALHUEN', 'Garces', 'Colchagua', 83.22, 1.0, 'Jose Miguel', NULL),
  ('LA LAJUELA', 'Garces', 'Santa Cruz', 74.12, 1.0, 'Jose Miguel', NULL),
  ('LIHUEIMO', 'Garces', 'Colchagua', 91.3, 0.0, 'Jose Miguel', NULL),
  ('LA RINCONADA', 'Garces', 'Pichidegua', 286.46, 1.0, 'Jose Miguel', NULL),
  ('LAS VERTIENTES', 'Garces', 'Pichidegua', 127.07, 0.0, 'Jose Miguel', NULL),
  ('LAS MAJADAS', 'Garces', 'Palmilla', NULL, 1.0, 'Jose Miguel', NULL),
  ('EL ROBLE', 'Garces', 'Placilla', NULL, 1.0, 'Esteban', NULL),
  ('EL HUAICO', 'Garces', 'Palmilla', 176.83, 1.0, 'Jose Miguel', NULL),
  ('MALLORCA', 'Garces', 'Molina', 32.84, 1.0, 'Jose Miguel', NULL),
  ('EL CONDOR', 'Garces', 'Morza', 63.07, 1.0, 'Jose Miguel', NULL),
  ('EL DESCANSO', 'Garces', 'Sagrada Familia}', 117.0, 1.0, 'Jose Miguel', NULL),
  ('Doña Cecilia-Doña Ines-Santa Maria-etc', 'Rafa Salgado', 'Talca', 132.5, 2.0, 'Esteban', NULL),
  ('ALFA LA HUERTA', 'Max Maroto', 'Rauco', 19.9, 2.0, 'Esteban', NULL),
  ('PENCAHUE', 'Max Maroto', 'Pencahue', 49.5, 0.0, 'Esteban', NULL),
  ('SANTA JULIANA', 'David del Curto ', 'San Clemente', 243.0, 2.0, 'Jose Miguel', NULL),
  ('FLOR ORIENTE', 'Toño Garcia', 'Talca', 107.4, 0.0, 'Jose Miguel', NULL),
  ('CAMARICO', 'Socoin', 'Camarico', 72.85, 0.0, 'Esteban', NULL),
  ('LOS CUNCOS', 'Socoin', 'San Rafael', 104.0, 0.0, 'Esteban', NULL),
  ('SAN CLEMENTE', 'Socoin ', 'San Clemente', 184.18, 0.0, 'Esteban', NULL),
  ('EL PICAZO', 'Garces', 'Pelarco', 92.79, 1.0, 'Esteban', NULL),
  ('EL ESPINO', 'Garces', 'Colbun', 97.61, 0.0, 'Esteban', NULL),
  ('EL ROSARIO', 'Garces', 'Linares-Llepo', 119.5, 0.0, 'Esteban', NULL),
  ('BODEGA', 'Garces', 'Longavi', 199.96, 1.0, 'Jose Miguel', NULL),
  ('CALIBORO', 'Garces', 'Longavi', 200.35, 1.0, 'Esteban', NULL),
  ('VILLASECA', 'Garces', 'Longavi', 74.28, 1.0, 'Esteban', NULL),
  ('HIGUERA ORIENTE', 'Monte Alegre', 'Longavi y Parral', NULL, 2.0, 'Esteban', NULL),
  ('ALTO LOS OLMO', 'Monte Alegre', 'Longavi y Parral', 126.0, 2.0, 'Esteban', NULL),
  ('CHUMPIRRO', 'Garces', 'Angol', 71.46, 3.0, 'Esteban', NULL),
  ('LA PERLA', 'Monte Alegre', 'Los Angeles', 60.0, 0.0, 'Esteban', NULL),
  ('VISTA HERMOSA', 'Monte Alegre', 'Rio Bueno', 65.0, 0.0, 'Esteban', NULL),
  ('CUN CUN', 'Monte Alegre', 'San José Mariquina', 65.0, 0.0, 'Esteban', NULL),
  ('SAN GABRIEL', 'Monte Alegre', 'Renaico', 34.0, 0.0, 'Esteban', NULL);

-- Campos importados: 107 (se omitió 1 fila sin datos reales de la planilla original)